### ISSUE TITLE
How to deal with multiple accused

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#16]
Not totally solved during ICC Alpha. Currently using composite images. 

https://github.com/robertocarroll/icc-alpha/issues/52

**Comment by taslaman** [comment]
Maybe we can use carousel for this and start with the highest ranking one in the case.

**Comment by robertocarroll** [comment]
The current suggestion for dealing with multiple accused is:

"a touch friendly carousel to be implemented with the buttons (left-right) to help in navigation." which seems fine to me as long as there's no issues around the relative importance of a defendant in a multiple defendant case, i.e. whoever is first in the carousel will be perceived as the most important person in the case unless the order is clear in some other way, e.g. alphabetical. 

Kyle and Simmi - do have any thoughts or concerns?

**Comment by kyleschaeffer** [comment]
Agreed – we plan on building a carousel in this area of our new UI to demonstrate the navigation between accused.

**Comment by robertocarroll** [comment]
I think we have agreement here, so closing this issue.
