### ISSUE TITLE
Article - How-the-court-works

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#23]
Latest version of the explanatory text is here (using content provided by PIDS): 

http://robertocarroll.com/icc-beta/about.html

**Comment by robertocarroll** [comment]
![03-05_how-the-court-works](https://cloud.githubusercontent.com/assets/1565953/4321874/96513aac-3f43-11e4-9cb5-f531a73d44f4.jpg)

**Comment by simmigaba** [comment]
Rob - Currently on Home Page we have below Text:
"Investigations and cases
The International Criminal Court investigates and, where warranted, tries individuals charged with the gravest crimes of concern to the international community: genocide, war crimes, and crimes against humanity. Find out more."
"Find Out more" is a hyperlink. So do I need to copy http://robertocarroll.com/icc-beta/about.html as it is as a new Page along with website Header and Footer and then this new Page will be opened when user clicks on "Find out more" hyperlink?

**Comment by robertocarroll** [comment]
We need to wait for the latest version of the content which will be worked in to an updated version of the about layout (latest version here http://robertocarroll.com/icc-beta/about.html ). 

Once the update content is in, as you say, it needs to be brought into the Sharepoint site with the header and footer and it would be a link from the home layout "find out more".

**Comment by simmigaba** [comment]
The updated version of the about layout is provided by Kyle which includes latest content and the header and footer: http://sharepoint13vm.cloudapp.net/sites/icc/about-icc

This is now linked to "Find out More".
![image](https://cloud.githubusercontent.com/assets/5706403/5813244/6f001acc-a0a0-11e4-9f60-1df36199b717.png)

The above is a Content Editor WebPart whose content can be updated by modifying below HTML File
/sites/icc/_catalogs/masterpage/icc/html/home-investigations.html
