### ISSUE TITLE
Case - Overview

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#33]
![01-01_case](https://cloud.githubusercontent.com/assets/1565953/4310119/7b6a325c-3ea3-11e4-97f0-3b22f77ea3be.jpg)
- Not resolved how to deal with multiple accused #16 - Single composite image?  
- Are we succeeding in providing context for a case? What more can we do? #8 
- Is it worth linking the ICC bios to the bios pages, so on the bio pages we can show which cases a judge is involved in - automatically? 
- Does the accused need his/her own page - to show more detail on bio, charges, etc.?

**Comment by robertocarroll** [comment]
Also - Calendar entry is currently missing.  Webstreaming link (when active) and calendar need to go below the introduction. E.G:

Next session: 9am (10am in -Situation country-) on 23 October 2014

OR 

Session ongoing until 5pm - Watch live (-link to webstreaming-)

**Comment by taslaman** [comment]
In most cases we will not have a calendar entry, as most of them are
dormant (Pre-Trial, or something else). We also need to get live data from
CMS, in order to properly test this. As for the second option, I don't
remember watch live was requested, so we would have to see how to implement
this.

**Comment by robertocarroll** [comment]
Just noting the outstanding points here: 
1. The calendar will power the next hearing part when available. Is it important for now or is it better to revisit this when we work on the calendar itself?  
   ![finder](https://cloud.githubusercontent.com/assets/1565953/5316531/a2b154ca-7c84-11e4-8f26-ba955577c3c8.jpg)
   1. The who is involved part will be powered by the people metadata (which Armin is working on). Again - do we revisit this bit of the case layout when we work on the people metadata part? 
2. At some point we discussed putting a link to watch line when it is active. It seems like a good idea from a user's perspective - bringing the information to them rather than making them hunt for it. I could imagine a var for isActive which is set to true when the current time and the next hearing time coincide, but perhaps that is too clumsy and inaccurate?

**Comment by simmigaba** [comment]
![image](https://cloud.githubusercontent.com/assets/5706403/5595077/2b31eb28-928f-11e4-9623-caadcbdaf182.png)

Will open another issue related for Calendar, Live Streaming and Bios to work in future Sprint.
