### ISSUE TITLE
Case - In the field

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#37]
![01-05_case](https://cloud.githubusercontent.com/assets/1565953/4311203/ce27ad4a-3eac-11e4-97a2-181f8f66defe.jpg)

Currently hardcoded. Need to double-check requirements, but currently needs to be a place for text and an image - related to a particular case. It would be good to be able to aggregate all this "in the field" content if necessary, e.g. on the outreach section.

**Comment by simmigaba** [comment]
Current Assumption is that data for "In the field" section do not have to be stored in Sharepoint backend list or library. In future the website content editors will directly edit this section with any info or can refresh the HTML file which is used to display the content for "In the field" section.
Need confirmation on this assumption.

**Comment by robertocarroll** [comment]
I think these do need to be stored as a Sharepoint list because viewing this content as part of the case is only one possible user scenario. A user might want to see all the ICC's work in affected communities in a single place regardless of the case/situation. 

Armin: what do you think about this? 
Simmi: how much extra work would it be?

**Comment by simmigaba** [comment]
This is not much of a work (8 - 12 hours). We can create a centralized Sharepoint list "In the field" with below fields:
1. Case Number
2. Situation Number
3. Description
4. Title
5. Image
6. Published Date
Then based on "Case Number" or "Situation Number", we can fetch the data for "In the field" section from the Sharepoint list for a given Situation or Case page (using a new web part) and can display the most latest entry for that Case or Situation based on Published Date. Then content administrators have to upload data to this Sharepoint list whenever they want to refresh the "In the field" section for any Case or Situation page.

**Comment by robertocarroll** [comment]
The case in the field will consist of:
Title 
Text

And then an image with a caption will be pulled through from the AV gallery. 

It is not necessary to see this information anywhere other than the case layout, so the requirements discussed above are not necessary and the current solution (editing text in HTML) is fine. 

Removing the dev tag from this issue and clearing the assignee as it's mainly about design.

**Comment by robertocarroll** [comment]
- Question: The case in the field will consist of title, text with an image/caption pulled from the AV gallery.
- MJ: Yes, the text will be one sentence, with a link to the situation in the field section, if possible.

We can include a link to the situation - in the field section. See #89 for the deeplinking into a section of a layout.

**Comment by simmigaba** [comment]
![image](https://cloud.githubusercontent.com/assets/5706403/5577960/1091d254-9043-11e4-9ce8-23921f3493ba.png)
