### ISSUE TITLE
What is the press kit (3.7)?

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#40]

**Comment by taslaman** [comment]
My understanding is that it is a page containing the links to specific
material created for Press and Media. I believe we will have these
tool-kits developed for various audience, like Academia and so on.

**Comment by robertocarroll** [comment]
How is that different from the landing layout for news (3.0) and the curated links for different audiences such as journalists (in the footer)?

**Comment by robertocarroll** [comment]
Press kit is part of Get involved (5.0) along with lots of other "information for" pages. A link to it will be featured from news along with press contacts. 

Closing this issue.
