### ISSUE TITLE
Article - Court record

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#50]
![03-01-article-court-record](https://cloud.githubusercontent.com/assets/1565953/4370280/12ed1ab0-4307-11e4-855c-82a715f5524e.jpg)

Information/values are pinned down but layout and design needs work. 

Breadcrumb for individual court records needs work - see #12

**Comment by simmigaba** [comment]
Additional Requirements:

Structure of the page
The page will be formed out of the following metadata and logic (the text in bold is the hard coded text on the page and entries in italics are metadata entries):
--Original Title--
--Full Document Number --
--Date Received-- | --Source (Language)-- | --Document Type (language)--
Case: --Case Name (Language)--
Situation: --Situation Name(Language)--
Filed during -- Phase of Case—phase
Download
Original document (note: based on the --Original--) --Language-- | Translation(s): --Language—
Related documents (shows the language of the site (English titles for the English site and French titles for the French site / if the appropriate language does not exist yet, shows the available one)
-- Main Document Number-- - -- Original Title—
Other related documents  
-- Main Document Number-- - -- Original Title—

The related documents and other related documents info is fetched based on mapping between document numbers and relationship type defined in Share point list – “Court Records Relationships” 

Links to the PDFs of the current document and its translations
Using “Full Document Number” and all of its permutations (-t…) generate direct links to the PDFs. The text in the link is equal to “Language” metadata field.
Example: The document ICC-01/04-01/06-2063 would have the following siblings:
ICC-01/04-01/06-2063 (original)-English document
ICC-01/04-01/06-2063-tFRA (translation)-French
The document links would be represented as:
Download
Original document (English) | Translation(s): Français

Links to the directly related documents
1.  Check the language first (url-language selector)
2.  Based on language, display related documents in the appropriate language
3.  If the language is not available show the next one (so if English is missing, show French)
4.  Display: “Main Document Number” – “Original Title”.

**Comment by simmigaba** [comment]
This webpart is implemented as per new requirements for CRM Module. Please refer to below snapshot for further details:

![image](https://cloud.githubusercontent.com/assets/5706403/5332553/a34b045a-7e80-11e4-9644-d60aa6ed463f.png)
