### ISSUE TITLE
Situation - Overview

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#53]
![02-01_situation](https://cloud.githubusercontent.com/assets/1565953/4370446/09d53fb4-4309-11e4-98c8-fcee6ba34609.jpg)

Provide a user with high-level overview - context and explanation - of why the ICC is operating in a particular place.

**Comment by simmigaba** [comment]
![image](https://cloud.githubusercontent.com/assets/5706403/5576933/7ad33d86-902c-11e4-8e11-a5f3eb717b13.png)
