### ISSUE TITLE
Situation - News

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#54]
![02-02_situation](https://cloud.githubusercontent.com/assets/1565953/4423681/f87cfc9e-4596-11e4-8900-290c69519e21.jpg)
- Main issue here is that these lists - news/court records/transcripts - contain information related ONLY to the situation, i.e. there's no case-related information here. 
- Yet the IA hierarchy (situation  > case) suggests that situation would show all records and the case would be a filter of that. 
- It's a quirk of the content that there is information related to the situation. 
- There's a sentence about this below but we have to assume users won't read it, so any other approaches are welcome.

**Comment by simmigaba** [comment]
It might be good to divide this issue into 3 issues -- "Situation - Court records",  "Situation -Transcripts" and "Situation - News" so that I can later move these tasks separately to Sprint backlog for coding and completion. Rob - Pls suggest.

**Comment by robertocarroll** [comment]
Split this issue:
- This issue is for news. 
- #69 is for court records. 
- #70 is for transcripts.

**Comment by simmigaba** [comment]
![image](https://cloud.githubusercontent.com/assets/5706403/5576042/a837964e-9015-11e4-9791-5fac1bc7113c.png)

The latest News are fetched from "Press Releases" document library present at /pressreleases site level. The WebPart fetches the "SituationNameEN" field from "General Information" SP list present at Situation Site level and then match it to "Related_x0020_To" field in "Press Releases" document library to retrieve all the News related to given Situation. The News records are retrieved sorted by "Publishing_x0020_Date" in descending order. 

The WebPart has "Num of Records" as configurable property to decide how many records to display in the News section. Default value is 3 records to display. 
Note -- I will open a new Issue regarding migrating the existing Press Releases ASP Pages to the new website. These ASP Pages will then be linked to News Title link.
