### ISSUE TITLE
How to make users aware of the difference between news and announcement?

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#60]
Users did not know the difference between "news" (press releases) and "announcements" (shorter, more frequent updates - like Twitter posts). Visual distinction?

see also #34 and #59

**Comment by kyleschaeffer** [comment]
Is it possible to combine these into one large "News" feed?  Would that work better for users?  Feed items could be distinguished through the UI with iconography or presentation style.

**Comment by robertocarroll** [comment]
There's a couple of reasons behind the separate areas: 
- Press releases are not necessarily regular or often but they do tend to represent the most important events in a particular case. So when a user arrives at the case layout, they can scan that list knowing that they're getting a fair summary of the latest + most important stuff. 
- Announcements is slightly different and came from the stakeholder desire to display Twitter feeds on the pages, but I argued that it was better to turn it the other way around and take control of bite-sized updates which can then be pushed to Twitter. Here's where I got the idea from: https://adactio.com/journal/6826 Beyond that, the type of content and the frequency of updates would be very different both from press releases and between different cases. 

Erika also suggests merging these feeds in #34 but what do you all think?

**Comment by kyleschaeffer** [comment]
Perhaps we can have the best of both worlds in this case.  Maybe we can, by default, give users a single news feed that contains all types of news in one feed.  We can also add a filtering mechanism that allows users to filter down to a specific type of news article (like press releases).  This is a fairly simple solution, and we could even save the users' preference in a cookie to keep their preference persistent as they come back to check for more updates.

**Comment by robertocarroll** [comment]
We've already defined that announcements are short, Twitter-like posts which give the ICC flexibility to highlight certain things, say certain things and respond to things without having to do a full press release. They could be on the home layout, situation layout or case layout - but not necessarily all situations and cases.

Here's a possible approach to announcements which creates an efficient way to manage them and makes use of Twitter as publishing channel. It follows the COPE approach - create once, publish everywhere:

https://www.dropbox.com/s/ffkt8rxks0i7gsq/icc-cope-2.pdf?dl=0

(Awaiting feedback from PIDS)

**Comment by simmigaba** [comment]
The Announcements functionality is verified by Armin. The Announcements to publish are created in centralized Announcements SP list. A specific Announcement can be related to multiple Case, Situation, etc and accordingly the latest Announcements are filtered and displayed on specific Case or Situation page. On Home Page, the latest Announcements across all Case, Situation etc are displayed. There is no other requirement to implement in context to Announcements functionality, as publishing to Twitter will be a separate functionality and there won't be any restriction on Announcement Body to limit to 140 Chars. Hence closing this issue.
