### ISSUE TITLE
Home - Investigations and cases overview

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#61]
![09-02_home](https://cloud.githubusercontent.com/assets/1565953/4370800/61cb74a4-430e-11e4-8290-ebffca73a24c.jpg)
- V important place to provide users with an overview of the ICC's investigative and judicial work.
- Intro sentence with link to 1.1 How the Court works (see #23)
- Numbers are also used in situation and stage templates.

**Comment by simmigaba** [comment]
Adding notes from other Issue here:

Remove the Investigations and cases title and make some other tweaks and this could become the "about" section. Find out more links to how the court works. Perhaps a teaser image would help here. This can't be called "Investigations and cases", but MJ is working towards an alternative, e.g. “Analyses, Investigations, Cases”, but it would include the court calendar, court records list, map and stages.

Rob - Do you have final requirement of what this section will be called and any changes that we need to do for beta phase?

**Comment by robertocarroll** [comment]
Sent an email about this to MJ, AT, JL - will add reply as soon as received.

**Comment by simmigaba** [comment]
![image](https://cloud.githubusercontent.com/assets/5706403/6102634/2fcfd26e-b060-11e4-8f26-5511f1cd45e4.png)

![image](https://cloud.githubusercontent.com/assets/5706403/6102674/be1f18a4-b060-11e4-97bd-2f67f09399db.png)
