### ISSUE TITLE
Home - Court records

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#62]
![09-04_home](https://cloud.githubusercontent.com/assets/1565953/4370843/cf1a7dca-430e-11e4-9003-46b0e47036df.jpg)
- List of latest three court records. 
- "More" link to search, sort and filter template 
- ICC Alpha feedback - somehow the ICC Alpha implementation failed to nail the user need - followed up with user but not clear why: 
  "[As journalists] we also have to check every day if there is something new that we don't know of. And we have to do that with all the other international organisations in The Hague, like ICJ, ICTY, OPCW etc.
  If there is nothing new that action should not take too much time. That is why the new documents should be in one place (and at the same time in the subsections where they belong). So can see in a glance what is new. Software to receive wire services even provides for story headlines to change colours when they have been read. So it is easy to catch up with the first unread story."

**Comment by kyleschaeffer** [comment]
How does this not meet user needs?  Doesn't the list here show the newest articles?  Clicking on the "more" link shows all articles, including newest.

The only other way we could make this more usable, that I can think of, is to introduce a sort of "read/unread" functionality into the court records listing.  Unread articles could have an indicator, and the court records heading could include a notification number (think red notification number tags that appear on top of app icons in iOS).  This would provide a great user experience, but I think the technical effort required would be very high, what do you think?

**Comment by robertocarroll** [comment]
I did follow up with the user and I think perhaps they didn't see the feature on the home layout rather than saw the feature and didn't find it easy to use. 

The functionality for read/unread sounds good but perhaps a lot of effort - Simmi? 

Not quite the same thing, but would a very clear :visited selector colour help so if they have been to that court record link it would show as faded?

**Comment by erikaORC** [comment]
If the issue is that users aren't easily seeing this on the home layout, how about condensing the "News" and "Announcements" feeds into one "Newsfeed" section. This eliminates the confusion surrounding what is the difference between "News" and "Announcements," and consequently allows us to move the "Court Records" web part up to where the existing "Announcements" feed appears.  When a user enters that page, they will then be immediately viewing the latest press release and photo, the current newsfeed, and court records all along one plane of vision.  It sounds like the Court Records might hold a much higher priority than we are currently giving it buried at the bottom.

**Comment by robertocarroll** [comment]
Your suggestion is close to my original suggestion, but the issue is - I think - that the top section: #59 is an overview of the entire court - not just the investigations and cases. 

There is a featured story, list of three press releases and list of three announcements, but these are not just related to cases and investigations - they could be about anything from across the entire range of the Court's work - including cases and investigations but also stuff to do with ASP, Justice Days, etc.    

So that's why the court records list ended up further down the layout. Admittedly that's bad for a particular set of users who come back to the ICC website (often many times a day) to check for new records, but perhaps the email alerts and other elements could help answer those needs.

**Comment by simmigaba** [comment]
The only possible thing we can do for this section is to generate some kind of dynamic message like "X Court Records published in last Y Hours". Where Y can be last 24 Hours or 12 Hours etc and X number of Court Records published in that timeframe to give returning users an idea that there is some new Records available to view. 
Even this dynamic message can be made more granular like "X Court Records published for Case Z in last Y hours" etc where Case Z can be the one with most number of Court Records published recently or in other words to say the most happening Case in Court at the moment. This kind of analytic info can also be shown in a new section next to Court Records with metrics like  Number of Court Records published in last Y hours with Case wise break up etc.
Any further thoughts on this?

Other minor UI changes can be done to make Case Value most prominent. At the moment its a Text value after Publishing Date. But we can use some CSS styling to make it more prominent as on Home Page the context of Case/ Situation is more important which is not required when User is viewing latest Court Records list directly on Situation or Case specific page.

**Comment by robertocarroll** [comment]
Great idea! I like the simple sentence:  "X Court Records published in last Y Hours".

**Comment by robertocarroll** [comment]
Also agree about the importance of situation / case in the court records list on the home layout. 

We could pick up some of the styling from here http://sharepoint13vm.cloudapp.net/sites/icc/court-records1 for the court records lists throughout the site. Or would that be a bit odd and jarring? It could be a nice way to indicate that it's a court record or it could look a bit over-the-top and out-of-place ... not sure.

**Comment by robertocarroll** [comment]
What did everyone think about using the styling from the search sort and filter for the court records lists on the home, situation and case layouts? Would this kind of thing look odd in the context of those layouts or would it help to identify the court records consistently throughout the site?

![court records-1](https://cloud.githubusercontent.com/assets/1565953/5579443/b2f7dcfc-9032-11e4-8ba2-d924f59b68ad.jpg) 

Related to #35 and #69

**Comment by simmigaba** [comment]
Yes I myself was planning to apply the same styling wherever we display list of Court Records and Transcripts on Home, Situation and Case page. So I think its a good suggestion and I will modify the Home, Case and Situation page sections accordingly.

**Comment by simmigaba** [comment]
Applied the styling from the search sort and filter for the court records lists on the situation and case layouts. Am not sure if it looks good. So further suggestions are welcome.
Situation Page:

![image](https://cloud.githubusercontent.com/assets/5706403/5606873/260c372a-946a-11e4-99e3-eb3bfa29ef75.png)

Home Page:

![image](https://cloud.githubusercontent.com/assets/5706403/5607172/84925472-9475-11e4-809d-95e87254e5f6.png)

Case Page:

![image](https://cloud.githubusercontent.com/assets/5706403/5606875/2d6e4cf6-946a-11e4-9814-fe75b1baf6a1.png)

**Comment by robertocarroll** [comment]
I've tweaked the padding a bit and increased the font size slightly on the title and I think it looks better, but I'm still not sure it is a good idea. Perhaps the blocks of colour are just too overbearing in this context? What does everyone else think? 

![icc- welcome to the international criminal court](https://cloud.githubusercontent.com/assets/1565953/5611944/391d3a98-94c5-11e4-93d5-7232a6d9950c.jpg)

**Comment by simmigaba** [comment]
![image](https://cloud.githubusercontent.com/assets/5706403/5727733/39a6fa7c-9b8b-11e4-8af0-aa6d1ca4237a.png)

regarding styling, I believe we can leave it at current state and may apply "visual polish" later based on user feedback on the beta website.
