### ISSUE TITLE
Home - Stages

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#63]
![09-06_home](https://cloud.githubusercontent.com/assets/1565953/4370891/4fbec86e-430f-11e4-9ca0-d506370cb25d.jpg)
- Users can see at a glance what activity is going on and go to more information / detail about each stage. 
- Same design pattern as stage - overview #43 but with space for brief introductory text.

**Comment by simmigaba** [comment]
![image](https://cloud.githubusercontent.com/assets/5706403/5815949/b8729ab6-a0c0-11e4-8884-3f37fb5b423b.png)

![image](https://cloud.githubusercontent.com/assets/5706403/5815984/2edc756e-a0c1-11e4-8ffd-45165d5780a4.png)
