### ISSUE TITLE
Home - Resource Library

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#65]
![09-08_home](https://cloud.githubusercontent.com/assets/1565953/4370952/4ad68e12-4310-11e4-988d-db59b8846141.jpg)
- Overview of 4.0 Resource Library
- Three featured sections/stories - Image, title, link, teaser
- Three links below to show links to more from those sections. 
- Currently hardcoded - so need development.  
- Also IA double-check - section title is a bit vague and use of "library" makes it seem v dated. Alternatives? Quick bit of user testing to validate?

**Comment by kyleschaeffer** [comment]
I'm curious to get Erika's feedback on this.  Perhaps the "Resource Library" heading is not needed at all.  We could make the section title for each of the three libraries more prominent, and use these as headings instead of the "Resource Library" text.

**Comment by robertocarroll** [comment]
Yes - I think "resource library" gives no indication of what might be below, it hides “Legal texts” which are v important and the word “library” makes the site seem outmoded (in my opinion). Another possible approach could be to:
1. Move 7.0 Jobs to be a subsection of 5.0 Get involved, but highlight and feature it prominently.
2. Make 4.1 Legal texts a top level heading. 
3. Rename 4.0 Resource library to Archive. The idea behind this is that all the important content in this section will be featured somewhere else on the site, e.g. reports on each organ layout, videos on the case layouts, etc. Users who are coming here are wanting to go into detail and this heading gives an indication of that. 

Although I think your suggestion could be better.

**Comment by erikaORC** [comment]
I really like the idea of moving "Legal Texts" out of the 4.0 section.  If we remove both "Legal Texts" and "Legal Research Tools" from 4.0, I think it might be more fitting and in mode to call that entire section something along the lines of "Media Center."  This could encompass all of the archives, in addition to being more descriptive for all videos, photos, publications, fact sheets, etc.  Archive would certainly work, but for me, I see the term "archives" akin to the outmoded "library."

If we then make "Legal Texts" a top level heading, is it not possible to give it it's old name of "Legal Texts and Tools" to make room for the legal research tools?

I might also suggest considering moving 7.0 Jobs into the 6.0 Contact Us heading.  I think it would possibly work for Get Involved, but it's also common practice to see a "Careers"  or "Jobs" link under a contact tab.  Just food for thought.  Might benefit from some quick testing.  Either way, I do agree that 7.0 Jobs does not need to be a top level heading.

**Comment by simmigaba** [comment]
Currently this section is hardcoded as HTML page  referenced in the Sharepoint Content Editor Webpart. No clarity how we will generate data for this section i.e. the data for below will be generated from which Sharepoint list or libraries?
-- Three featured sections/stories - Image, title, link, teaser
-- Three links below to show links to more from those sections. 
And when user clicks on links like "Photos", "Understanding the ICC:, etc then the link should re-direct to which page and what content has to be displayed on those pages?  
Also can you pls tell if all the data for this section will be created new for the new website or migrated from the existing website. If from the existing website, then pls give example of how this data is currently displayed in the existing website.

**Comment by robertocarroll** [comment]
- 4.1 legal texts is this section on the current site: http://icc-cpi.int/en_menus/icc/legal%20texts%20and%20tools/Pages/legal%20tools.aspx - with added HTML versions of the Rome Statute and Elements of Crimes.
- 4.4. Reports will aggregate all content of the type report in a search, sort and filter template. Content which is currently spread around the site, e.g. http://icc-cpi.int/en_menus/icc/structure%20of%20the%20court/office%20of%20the%20prosecutor/reports%20and%20statements/statement/Pages/index.aspx (minus statements) 
- 4.5 Publications is all the factsheets etc which the ICC produce. Again probably best on a search, sort and filter template so people can find what they are looking for quickly. 
- 4.6 AV gallery is the multimedia archive project which is still a separate project (Armin?) as referenced here: https://github.com/robertocarroll/icc-alpha/issues/25
- 4.7 ICC Library is a way for ICC staff to get to information about the actual library at the ICC - for borrowing books etc. 

Many bits of content, e.g. a particular video or a set of reports, will be shown in other places, but here is where people can go to "view all" or get an aggregate view on all content of a particular type.

**Comment by robertocarroll** [comment]
That link to the AV Gallery statement of work was broken. Here's an updated link: 
https://www.dropbox.com/s/1vc11mmjtg7xyl3/AV-library-SOW.docx?dl=0

**Comment by simmigaba** [comment]
As discussed with Armin in e-mail, no more changes required for Resource Library section in the beta dev phase. This section will continue to remain as Content Editor web part and Content creators will  modify the HTML links etc in future as require. Also the look and feel of this section might change based on suggestions to be given by re-branding team (RY). To change the content of this section, modify the HTML file - "home-resourcelibrary.html" present in library http://sharepoint13vm.cloudapp.net/sites/icc/_catalogs/masterpage/icc/html/
