### ISSUE TITLE
Court Records Management Module - Integration between TRIM and Website

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-beta#71]
Creating this issue to track integration part of Court Records Management module separately as it will be developed by Integration team in ICT.

**Comment by simmigaba** [comment]
Prepared the design document for TRIM-Sharepoint Integration bridge and sent it to Integrations team for review.

**Comment by robertocarroll** [comment]
Feedback from CMS (noting here from call):
- Extra "subject matter" field - metadata field required (AT - details) 
- Confidentiality - don't get confidential documents - even reference number. 
- Disclaimer for missing language version: "The document is only currently available in LANGUAGE"
- Default delay to upload
- Ability to override delay, i.e. priority upload checkbox.

AT or SG to update this issue once finalised.

**Comment by simmigaba** [comment]
The requirements for TRIM-Sharepoint integration bridge are finalized. The updated design document is sent to Integration team in ICT for implementation.

**Comment by simmigaba** [comment]
TRIM-Sharepoint Integration bridge design document is updated and is available at below location:
http://sharepoint13vm.cloudapp.net/sites/icc/Documents/TRIM-SharePoint%20Integration%20Bridge%20CRM%20Automation.docx
This bridge will be implemented by ICT section as a separate project.
