### ISSUE TITLE
Twitter accounts - for court records, situations, etc

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#72]
Possible useful Twitter accounts:
- A Twitter account which posts all new court records. Automatic updates. Only court records - nothing else. Truncated title, link to record. 
- Twitter accounts for press releases related to investigations and cases. Automatic updates. 
- Twitter accounts for particular situations and/or cases?  
- A Twitter account for job vacancies

**Comment by kyleschaeffer** [comment]
I like this idea, definitely adds a new way to engage with the ICC, and can link back to content on the website.
