### ISSUE TITLE
Will a defendant have his or her own page? 

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#74]
This is related to issue #16 - Not enough room at the top of the case layout to show all the details, especially when more than one accused. 

Possible to link to another page for each defendant. The page would sit below the case page:

http://icc-cpi.int/situtation/case/accused
http://icc-cpi.int/kenya/ruto-sang/ruto 

There's a few problems with this approach: 
- It forks the journey from the defendants layout (10) 
- ICC feedback that it gives too much prominence and importance to a defendant. 

Details of the discussion during ICC Alpha are here: https://github.com/robertocarroll/icc-alpha/issues/29

**Comment by robertocarroll** [comment]
From an information management perspective, it makes sense to have a non-exhaustive list of charges as a separate page linked from the top of the case layout. 

The top of the case page shows each accused and a summary of charges. Click on a link and go to a page with full list. 

There are some objections to each accused having his or her own page - focus should be on cases not individuals - but perhaps this can be taken into account while maintaining the logical structure. 

Here's an example of what could go on that page (from the case information sheet):
![rutokosgeysangeng pdf page 1 of 3](https://f.cloud.github.com/assets/1565953/1566479/a25fb13c-508f-11e3-8fbd-de2ffb9d842d.jpg)
![preview](https://f.cloud.github.com/assets/1565953/1566494/d0ef882e-508f-11e3-8003-e33caf8f434b.jpg)

**Comment by robertocarroll** [comment]
The only extra technical requirement is the ability to add these pages in the correct place in the url structure and link to them from the accused name at the top of the case layout. Perhaps we could describe that page as "charges" and put that in the url:
- http://icc-cpi.int/situtation/case/charges-accused

## Lubanga case
- http://icc-cpi.int/situtation/drc/lubanga/charges-lubanga

## Ruto and Sang case
- http://icc-cpi.int/situtation/kenya/ruto-sang/charges-ruto 
- http://icc-cpi.int/situtation/kenya/ruto-sang/charges-sang

**Comment by robertocarroll** [comment]
Armin: there was objections to a defendant having his or her own page, but it seems vital as a way to display the non-exhaustive list of charges and other information. 

Are there any objections to the approach suggested above? Where the pages would be charges rather than defendant? e.g. http://icc-cpi.int/situtation/case/charges-accused The defendant's name at the top of the case layout would be a link to this charges page. 

This seems to answer the objections and provide the functionality we need. Please can you confirm.

**Comment by simmigaba** [comment]
Implemented Carousel on Case Page to show Multiple Accused for a given Case. The information displayed for Accused is as below:

![image](https://cloud.githubusercontent.com/assets/5706403/5595097/974b2824-928f-11e4-844d-7b89c1a8b845.png)

As per last e-mail response by Armin:
"Accused pages: I would say no. We would not have anything more to offer for that page. We will be showing all information on the case page. I asked for feedback on this issue from Fadi (my supervisor) and will let you know as soon as I receive it."

-- Need final confirmation from Armin before this issue can be closed.

**Comment by taslaman** [comment]
Dear Simmi and Rob,

I had one final consultation with Fadi about this and both of us think that there is no need for the defendant page, as it would further complicate the case sub-site and would not contain a lot of information. The non-exhaustive list (Alleged crimes) is always related to the case and never to the accused. We would recommend the following:

The accused library can contain all of the current column structure. 
The Alleged crimes should be a part of the case page in some form – it can be a direct text entry on a page, or can be in a custom list. This information will not change so much, so it is fine either way. It might be good to have this wrapped in an expandable div so we would save some space.

The case page vertical layout should be:
First row:  description of the case (intro) + Accused information
Second row: Alleged Crimes (link – expand) + link to the Case information sheet
Third row: Timeline (as we agreed in 2014)

And the rest can be the same as it is now.

**Comment by simmigaba** [comment]
Dear Armin - Thanks for the response. We already have Custom list called "General Information" at each Case Site level from which we fetch other Info about Case like Name, Title, Summary, Phase etc. In the same SP list, I can add another column (Multiple lines of Text) for Alleged Crimes and accordingly that info will be displayed on Case Page. 
Regarding UI, if you visit: http://sharepoint13vm.cloudapp.net/sites/icc/drc/lubanga
we do have a empty placeholder which may be sufficient to display the information in a Card with vertical scrollbar (same way we have Accused info currently). Or simply a link with expandable div (same way currently we have link for "Who is involved?" on Case Page)

![image](https://cloud.githubusercontent.com/assets/5706403/5644848/15b96d22-968e-11e4-8191-4eb4fe0438e4.png)

What do you think?

**Comment by robertocarroll** [comment]
I didn't realise the non-exhaustive charges were per case not per accused. That explains why the proposed solution doesn't work.

However I do think the top of the case layout - overview - is already way to cluttered and confusing. We're trying to cram too much information in already and I think (from a user experience / design perspective) the non-exhaustive charges are the straw that will break the back of this layout and turn it into a bad experience. 

![will a defendant have his or her own page issue 74 robertocarroll_icc-beta](https://cloud.githubusercontent.com/assets/1565953/5645062/a42a2474-9662-11e4-9dcb-509a68af91d2.jpg)

Rather than using the space you suggest (which also incorrectly associates the charges visually with the accused rather than the case), I think this could be an opportunity to scale back. The volume of information - "who is involved" and the "non-exhaustive charges" (300-500 words) - is simply too great to fit in the space. Even if you do manage to fit it in, the expandable boxes could be a nightmare to use, i.e. the full text might not even fit within the visible window because it is so long. 

Perhaps instead we could add a link after the description saying "See non-exhaustive list of charges" and incorporate the link to "trial chamber I" into the description. Each of these would be separate pages. That would provide more flexibility and help to return the case layout overview to a good experience.

What do you think?

**Comment by robertocarroll** [comment]
I didn't realise the non-exhaustive charges were per case not per accused. That explains why the proposed solution doesn't work.

However I do think the top of the case layout - overview - is already way to cluttered and confusing. We're trying to cram too much information in already and I think (from a user experience / design perspective) the non-exhaustive charges are the straw that will break the back of this layout and turn it into a bad experience. 

![will a defendant have his or her own page issue 74 robertocarroll_icc-beta](https://cloud.githubusercontent.com/assets/1565953/5645062/a42a2474-9662-11e4-9dcb-509a68af91d2.jpg)

Rather than using the space you suggest (which also incorrectly associates the charges visually with the accused rather than the case), I think this could be an opportunity to scale back. The volume of information - "who is involved" and the "non-exhaustive charges" (300-500 words) - is simply too great to fit in the space. Even if you do manage to fit it in, the expandable boxes could be a nightmare to use, i.e. the full text might not even fit within the visible window because it is so long. 

Perhaps instead we could add a link after the description saying "See non-exhaustive list of charges" and incorporate the link to "trial chamber I" into the description. Each of these would be separate pages. That would provide more flexibility and help to return the case layout overview to a good experience.

What do you think?

**Comment by robertocarroll** [comment]
Another option - if there's reasons not to have separate pages - is to place this information much lower down the page (below the ask the court) and have anchor links to those sections. That would keep the information on the case layout without cluttering the overview.

**Comment by taslaman** [comment]
If we go with a separate page for the Alleged crimes, what would we have on it? How it would look like. It might be looking rather empty. I would agree that we really need to think critically about the volume of data we are going to present to users on the case pages, but alleged crimes are kind of a hart-and-soul of the case page in the pre-trial and trial phase, as they describe what, where and why. I am not against separate pages, but they need to be necessary. What I want to say is that I don't want to end up with the cases pages looking like the current ones, where information is fragmented in different pages. The new principle works so much better in that respect.

**Comment by robertocarroll** [comment]
I think we are both trying to advocate an approach whereby the very, very important information is displayed in the overview and if a user is interested in finding out more, they can click to go and see that information.

My confusion - which I imagine could also be one for a user of the site - is what all this information is and what it means and what is important. That's a decision that we need to take on behalf of the user without cutting off the ability to find the rest of the information. At the moment we have: 

## Per case
1. Short case title
2. Full case title 
3. Case code
4. Case stage (link to stage)
5. Case description (100 words summarising the latest overall status and developments in the case)
6. Optional calendar schedule
7. Link to pdf

## Per accused
1. Name
2. Accused state
3. Accused description  (30 words about who the person is) 
4. Accused charges (50 words summarising charges)

This seems like a manageable amount of very, very important information with clear associations of each item and no repetition. 

The "who is involved" and the non-exhaustive list of charges (per case) are longer (up to 500 words) and difficult to compress/summarise so naturally don't fit in the overview. Having one expandable section was just about OK but I think it wrong to have two. 

When you say:

> alleged crimes are kind of a heart-and-soul of the case page in the pre-trial and trial phase, as they describe what, where and why.    

are we not already summarising these in the case description and the accused charges? If not, I am confused about the relationship between everything.  

What did you think to the idea of placing "who is involved" and the non-exhaustive list of charges at the bottom of the case layout with anchor links from the overview?

**Comment by robertocarroll** [comment]
Also, I agree that fragmentation would be bad. It still comes down to placing the very, very important at a glance and the rest somewhere else - either (i) hidden with click to expand, (ii) further down the page with an anchor link, (iii) on a new page. 

I'm not arguing for the new pages rather against cramming so much at the top.

**Comment by taslaman** [comment]
We believe that the introduction to the case should be sufficient to describe the Alleged crimes. We also think that Case information sheet would be a better location for the detailed explanation of the charges and other milestones in the case. 

Now, I remember that initially we wanted to have a CIS as a page but with a possibility to print as a PDF. I don't think we would have enough control over the look and feel of the PDF, but if we can have a MS Word document in a library which we can amend, this would be perfectly fine. The PDF can be generated from this MS Word file by SharePoint (please correct me if I'm wrong Simmi). 

Also, it would be great if the HTML page would use the same information that we put in the MS Word file, so we would avoid duplication.

What do you think about this?  Would this solve the problem?

**Comment by simmigaba** [comment]
Yes I agree that introduction to the case should be sufficient to describe the Alleged crimes. And more detailed info can be in Case Information Sheet. Then I believe we don't need any further changes for existing Case Page UI to display Alleged Crimes. 
At the moment CIS is a PDF document present in document library at Case site level. It can be anything i.e. HTML Page, Word document or PDF etc as the webpart just displays the link to whatever CIS document is uploaded. If you are looking to edit word document and for automatic conversion, then I need to implement that logic in custom SP / Nintex workflow i.e. whenever the CIS word document is updated in the library, then auto generate PDF page and update in same document library which will then be displayed as download link on Case Page. Alternatively, Content Creator can also generate PDF from Word using MS Word etc and can update the PDF version whenever the Word version is modified.
I am not sure whats use of HTML version, in current Case Page design we only have "download" link to CIS.

**Comment by taslaman** [comment]
I believe we can then use Ms Word files to edit the CIS and content creator to generate new PDF files upon approval of the CIS. What do you think about that?

**Comment by simmigaba** [comment]
Yes that will work. We can have both MS Word and PDF versions in the library. Content Creator can modify MS word, get approved, generate PDF and update in the document library at Case site level.
Then website user can download the CIS PDF version from the case Page. And as discussed above, the Introduction to Case itself will be sufficient to give overview of Alleged Crimes etc.  
Therefore I will close this issue.

**Comment by robertocarroll** [comment]
The main issue here is duplication of information: how can the user know what information is in what format unless the intended purpose of the different formats is made clear? 

At the moment, the case information sheet is clearly shown to be an object intended to download / print. The user can therefore presume that there is intended duplication - "I am looking at the website and I actually want to print something so here is a special object prepared by the ICC for that purpose." 

If you remove that purpose from the case information sheet and simple put it up on the website as another web page, then the user doesn't know what information is where and consequently has to choose between CIS and case layout (without any basis for the decision) or look at both. 

Almost all of the information from the case information sheet has been incorporated on the case layout, it would be a huge step back to dilute and waste the user's attention by wastefully and needlessly duplicating so much information.

**Comment by simmigaba** [comment]
Hi Rob - I am not sure if I understood your last comment properly. The web site will see Introduction to Case which is at the moment below text:

"Thomas Lubanga Dyilo was found guilty of committing as co-perpetrator, the war crimes of the enlistment and conscription of children............ This is the first verdict and sentence issued by an ICC Trial Chamber."

The Idea is that Introduction to Case text give overview info about Alleged Crimes and for detailed info users can download CIS PDF document. Users will see a download link to CIS PDF i.e. there won't be any change for the Case Page as we have now.
What me and Armin were discussing was that what's the easiest way for Website content Administrators to modify the content in CIS PDF in future as its hard to directly edit the PDF. So options where that we internally also maintain a CIS version in HTML/ Word which Content Administrators can easily modify, get the content approved and then convert it to PDF and update in the underlying SP document library.
So for website users they will just see CIS download link PDF version and will not see any other formats i.e. CIS HTML Page or Word document. 
So I am not sure what exactly is your concern. Please clarify.

**Comment by robertocarroll** [comment]
I was referring to this: 

> We also think that Case information sheet would be a better location for the detailed explanation of the charges and other milestones in the case.

which I disagree with. Most of the information from the case information sheet has been incorporated on to the case layout, e.g. milestones are in the key developments timeline. 

I was worried about the case layout and the case information vying for the user's attention if the intended uses are removed. But if the result is as you say: that the case information sheet remains clearly marked as "print" case information sheet, then that's OK.

**Comment by simmigaba** [comment]
Thanks for clarification. My understanding is same as yours that CIS should just remain as print and download option. All the relevant info to show to user i.e. key milestones, Timeline, Defendant basic Info, Alleged Crimes Overview is currently displayed on main Case Page.
If we make CIS as HTML Page then it will be duplicate Info in terms of what's displayed on main Case Page and what CIS HTML Page will contain which is not a good strategy and will create confusion as you also pointed out.
CIS PDF might have additional info about Defendant, Alleged Crimes etc which is not displayed on main Case Page but then my understanding is that we are NOT putting all that additional info on main Case Page with an assumption that it is not relevant there.
