### ISSUE TITLE
Style tiles

### ISSUE THREAD

**Issue by kyleschaeffer** [robertocarroll/icc-beta#82]
I have created three **style tiles** to help create a discussion around the creative direction of the ICC website.  Please take a look at the following images and share your feedback.  Specifically, I'd love to hear your feedback on the following:
1. Which **color scheme** do you prefer?  Tile 1 uses cool colors, 2 uses a warm colors, and 3 presents a variety of the two.
2. Which **fonts** do you prefer for **headings**? Which heading case do you prefer (sentence case, title case, uppercase)?
3. Which **fonts** do you prefer for **paragraphs**? Do you have a preference for alignment (left vs. justified)?
4. Which **header style/logo style** do you prefer?
5. Do you have a preference on **button/call to action** styles?
6. Do you prefer the **"open" style** (tile 1), or the **boxed style** (tiles 2 and 3) for content?
7. Do you prefer **soft edges** (tiles 1 and 2), or **harder, sharper edges** (tile 3)?
8. Do you prefer **flat style** (tiles 1 and 3, notice buttons and elements do not have shadows or borders) or **textured style** (tile 2, notice how buttons and content boxes have drop shadows and borders)?
9. Do you have any additional feedback or comments?
## Tile 1 (click to expand)

![tile1](https://cloud.githubusercontent.com/assets/1176150/4703342/259cd04c-586a-11e4-93b5-9e86a7668cb8.jpg)
## Tile 2 (click to expand)

![tile2](https://cloud.githubusercontent.com/assets/1176150/4703346/2ab97de6-586a-11e4-9819-82dfe0dfbdb1.jpg)
## Tile 3 (click to expand)

![tile3](https://cloud.githubusercontent.com/assets/1176150/4703349/2fe49530-586a-11e4-9c95-8847639b16f8.jpg)

**Comment by robertocarroll** [comment]
Recording the feedback (sent by email) and closing this issue: 
- Which color scheme do you prefer? **Tile 1**
- Which fonts do you prefer for headings? **Tile 1**
- Which fonts do you prefer for paragraphs? **Tile 1**
- Which header style/logo style do you prefer? **Tile 2 (In 1, the logo is too small, Sonia likes the dominance of the logo in Tile 3, all have potential)**
- Do you have a preference on button/call to action styles? **Tile 1, but it depends on the content, we like how for the most part they blend into the page, but sometimes if we want to draw attention to content, they could be more obvious.**
- Do you prefer the "open" style (tile 1), or the boxed style (tiles 2 and 3) for content? **Tile 1, with option for Tile 2 or other boxed style when there is a reason to really separate the content.**  
- Do you prefer soft edges (tiles 1 and 2), or harder, sharper edges (tile 3)? **soft edges**
- Do you prefer flat style (tiles 1 and 3, notice buttons and elements do not have shadows or borders) or textured style (tile 2, notice how buttons and content boxes have drop shadows and borders)? **Flat**
- Do you have any additional feedback or comments? **We could explore using the outline of the Permanent Premises in the header or footer.**
