### ISSUE TITLE
Cards - possible approach to context and explanation 

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#88]
I’ve been mulling over how we can provide context and explanation by pulling in relevant information and making it relevant to the moment.

There’s a few places where this approach is relevant:
1. Ask the Court - questions and answers
2. How the Court works - tall, scroll page explaining the Court - http://robertocarroll.com/icc-beta/about.html
3. The Rome Statute - explanations and relevant decisions - http://robertocarroll.com/icc-beta/rome-statute.html#article21

I’ve put together the first draft of a possible approach (attached) using “cards": 

https://www.dropbox.com/s/db5620rwjauozu1/ICC-Beta-cards.pdf?dl=0

**Comment by kyleschaeffer** [comment]
From a user experience perspective, I think this approach is great.  I love the idea and would love to implement this as you've suggested in your draft.  From a technical perspective, however, I'm not sure how difficult this will be.  In the back-end, the content which in a typical SharePoint site is contained in a few common fields across many pages, would have to be broken up and split into many fields.  Not only that, but we would also have to associate other related content (i.e. horizontal cards) to each of those fields/pieces of information.  Maybe it's not as difficult as I'm thinking, we should probably pose the idea to the technical team to get feedback.

Another concern is that this would make many of our content pages essentially hard-coded HTML and JavaScript.  I'm not sure how flexible the ICC staff wants to make this content, but any pages built like this would probably need to be crafted by someone with experience with HTML, CSS, and JavaScript.  Easy for us, but maybe not for the people in charge of governing the site.

Let me know what you think. This would be fun if we could work it in, but for now I'll play the Devil's advocate such that we consider the advantages and disadvantages of the technique.

**Comment by robertocarroll** [comment]
Glad you like the idea. How about we break it down into two parts:
1. Use cards for the Ask the Court section. Following the Vox example, each card represents a question and answer and can be stacked and re-arranged in many different ways. This would be possible in Sharepoint would it? Each card would be an article with the question as the title. 
2. Once we have implemented that approach consider if it is worth trying to take this further - by using these cards to provide context.

**Comment by taslaman** [comment]
I believe the "cards approach" is something that we can definitely explore.
As you mentioned in the document, Ask the Court would work very well with
this approach. As for the rest of the content, we would have to work on
these individual pages, especially pages like How the Court Works and
others like that. I believe we would have to hand-craft most of these pages
and that is fine by me. We would need to have connections to the dynamic
data (like people, questions and such), and this can be done by web parts.
We would also need styles to make all of this easier to assemble. I would
be happy to work on this, so I'm in.

Kind regards,
armin.

**Comment by robertocarroll** [comment]
After discussions with KS and JL, I think we have to park the cards idea until everything else is done and see how much time we have left. 

Marking it "post-beta"

**Comment by robertocarroll** [comment]
Closing post-beta so we have a clear run at the issues.
