### ISSUE TITLE
Ability to deeplink into section of layout

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#89]
On the case / situation / home and other layouts, each section had its own ID so that it could be linked to and when the user clicked on the menu on the right it added the hashID to the url. This seemed like a sensible approach which I think should continue into ICC Beta. I'm noting it here so we don't forget. 

Also with the timeline, would it be good to be able to link to a particular point, e.g. 
/drc/lubanga#key-developments and then the slide number.

**Comment by robertocarroll** [comment]
I wanted to add a note about how the home layout could work in the context of such links:

## icc-cpi.int/#News

![icc- welcome to the international criminal court](https://cloud.githubusercontent.com/assets/1565953/5502945/e14b8f36-8768-11e4-89f5-efbc907577c2.jpg)

## icc-cpi.int/#about

_Remove the Investigations and cases title and make some other tweaks and this could become the "about" section. Find out more links to how the court works. Perhaps a teaser image would help here._

![icc- welcome to the international criminal court-1](https://cloud.githubusercontent.com/assets/1565953/5502969/210f0148-8769-11e4-9f10-d141dda1f9f9.jpg)

## icc-cpi.int/#investigations-and-cases

This can't be called "Investigations and cases", but MJ is working towards an alternative, e.g. “Analyses, Investigations, Cases”, but it would include the court calendar, court records list, map and stages. 

## icc-cpi.int/#states-parties

_Clear from current home layout_

## icc-cpi.int/#resource-library

_Clear from current home layout_

## icc-cpi.int/#get-involved

_Clear from current home layout_

Does this work/make sense?

**Comment by simmigaba** [comment]
Yes make sense. I will create links for different sections accordingly.

**Comment by simmigaba** [comment]
Div ids created accordingly for Home, Situation and Case pages to have URLs like:
http://sharepoint13vm.cloudapp.net/sites/icc/#news
http://sharepoint13vm.cloudapp.net/sites/icc/#about
http://sharepoint13vm.cloudapp.net/sites/icc/#states-parties
http://sharepoint13vm.cloudapp.net/sites/icc/#resource-library
http://sharepoint13vm.cloudapp.net/sites/icc/#get-involved

http://sharepoint13vm.cloudapp.net/sites/icc/drc/#overview
http://sharepoint13vm.cloudapp.net/sites/icc/drc/#news
http://sharepoint13vm.cloudapp.net/sites/icc/drc/#courtrecords
http://sharepoint13vm.cloudapp.net/sites/icc/drc/#cases
http://sharepoint13vm.cloudapp.net/sites/icc/drc/#inthefield
http://sharepoint13vm.cloudapp.net/sites/icc/drc/#ask-the-court

http://sharepoint13vm.cloudapp.net/sites/icc/drc/lubanga/#overview
http://sharepoint13vm.cloudapp.net/sites/icc/drc/lubanga/#news
http://sharepoint13vm.cloudapp.net/sites/icc/drc/lubanga/#courtrecords
http://sharepoint13vm.cloudapp.net/sites/icc/drc/lubanga/#keydevelopments
http://sharepoint13vm.cloudapp.net/sites/icc/drc/lubanga/#inthefield
http://sharepoint13vm.cloudapp.net/sites/icc/drc/lubanga/#ask-the-court

**Comment by robertocarroll** [comment]
Ok. Great. Leaving this open until we have confirmation that the home/section approach outlined above is ok. Related to #61

**Comment by simmigaba** [comment]
Closing this issue as nothing more to be done here and related issues 61 is also Closed.
